"""empty message

Revision ID: 12b4fe1b20c3
Revises: 60237f523a7d
Create Date: 2022-07-18 20:16:34.839900

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '12b4fe1b20c3'
down_revision = '60237f523a7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('linkedin_events_details', 'display_time', type_=sa.Text(), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('linkedin_events_details', 'display_time', type_=postgresql.TIMESTAMP(), nullable=True)
    # ### end Alembic commands ###
