"""empty message

Revision ID: 4d327ad16da9
Revises: 12b4fe1b20c3
Create Date: 2022-07-20 00:20:25.043090

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4d327ad16da9'
down_revision = '12b4fe1b20c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('linkedin_employees_details', 'birthdate')
    op.add_column('linkedin_employees_details', sa.Column('birthdate', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('linkedin_employees_details', 'birthdate')
    op.add_column('linkedin_employees_details', sa.Column('birthdate', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
