"""empty message

Revision ID: 720a013e8e7c
Revises: 
Create Date: 2022-07-14 20:34:21.480708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '720a013e8e7c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('linkedin_companies_base_details',
    sa.Column('internal_id', sa.BigInteger(), nullable=False),
    sa.Column('link', sa.Text(), nullable=True),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('address', sa.JSON(), nullable=True),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('universal_name', sa.Text(), nullable=True),
    sa.Column('employee_count', sa.JSON(), nullable=True),
    sa.Column('specialities', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('followers_count', sa.BigInteger(), nullable=True),
    sa.Column('tagline', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('founded_on', sa.Integer(), nullable=True),
    sa.Column('industry', sa.ARRAY(sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('internal_id')
    )
    op.create_table('linkedin_employees_details',
    sa.Column('public_id', sa.Text(), nullable=False),
    sa.Column('firstName', sa.Text(), nullable=True),
    sa.Column('lastName', sa.Text(), nullable=True),
    sa.Column('headline', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('industryName', sa.Text(), nullable=True),
    sa.Column('locationName', sa.Text(), nullable=True),
    sa.Column('student', sa.Boolean(), nullable=True),
    sa.Column('geoCountryName', sa.Text(), nullable=True),
    sa.Column('geoLocationName', sa.Text(), nullable=True),
    sa.Column('experience', sa.ARRAY(sa.JSON()), nullable=True),
    sa.Column('education', sa.ARRAY(sa.JSON()), nullable=True),
    sa.Column('languages', sa.ARRAY(sa.JSON()), nullable=True),
    sa.Column('publications', sa.ARRAY(sa.JSON()), nullable=True),
    sa.Column('certifications', sa.ARRAY(sa.JSON()), nullable=True),
    sa.Column('volunteer', sa.ARRAY(sa.JSON()), nullable=True),
    sa.Column('honors', sa.ARRAY(sa.JSON()), nullable=True),
    sa.Column('email_address', sa.Text(), nullable=True),
    sa.Column('websites', sa.ARRAY(sa.JSON()), nullable=True),
    sa.Column('twitter', sa.ARRAY(sa.JSON()), nullable=True),
    sa.Column('birthdate', sa.DateTime(), nullable=True),
    sa.Column('phone_numbers', sa.ARRAY(sa.JSON()), nullable=True),
    sa.Column('followable', sa.Boolean(), nullable=True),
    sa.Column('followersCount', sa.BigInteger(), nullable=True),
    sa.Column('connectionsCount', sa.BigInteger(), nullable=True),
    sa.Column('skills', sa.ARRAY(sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('public_id')
    )
    op.create_table('linkedin_events_details',
    sa.Column('event_id', sa.Text(), nullable=False),
    sa.Column('state', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_time', sa.DateTime(), nullable=True),
    sa.Column('attendee_count', sa.BigInteger(), nullable=True),
    sa.Column('company_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['linkedin_companies_base_details.internal_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('linkedin_jobs_details',
    sa.Column('job_id', sa.BigInteger(), nullable=False),
    sa.Column('job_state', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('listed_at', sa.DateTime(), nullable=True),
    sa.Column('expire_at', sa.DateTime(), nullable=True),
    sa.Column('company_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['linkedin_companies_base_details.internal_id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('linkedin_posts_details',
    sa.Column('link', sa.Text(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.Column('commentary', sa.JSON(), nullable=True),
    sa.Column('company_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['linkedin_companies_base_details.internal_id'], ),
    sa.PrimaryKeyConstraint('link')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('linkedin_posts_details')
    op.drop_table('linkedin_jobs_details')
    op.drop_table('linkedin_events_details')
    op.drop_table('linkedin_employees_details')
    op.drop_table('linkedin_companies_base_details')
    # ### end Alembic commands ###
